[package]
name = "arceus"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "arceus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", features = ["multipart", "json"] }
tokio = { version = "1", features = ["full"] }
cpal = "0.18"
hound = "3.5"
anyhow = "1"
enigo = "0.6"
tauri-plugin-global-shortcut = "2"
dirs = "6"
strsim = "0.11"
rodio = { version = "0.22", default-features = false, features = ["playback"] }
serialport = "4.9"
whisper-rs = { version = "0.16", features = ["vulkan"] }
windows = { version = "0.62", features = ["Win32_UI_WindowsAndMessaging", "Win32_System_Threading", "Win32_System_ProcessStatus", "Win32_Foundation"] }
once_cell = "1.21.4"
screenshots = "0.8.10"
image = "0.25.10"
chrono = "0.4.45"
urlencoding = "2"
futures = "0.3.34"
chromiumoxide = "0.9.1"
base64 = "0.22"
dotenvy = "0.15"
unicode-normalization = "0.1"
dunce = "1"
